volumes:
  postgres-db-test:
  redis-data-test:
  logs-data-test:

networks:
  test-network:
    driver: bridge

services:
  db-test:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env.test
    volumes:
      - postgres-db-test:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d test']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - test-network

  redis-test:
    image: redis:7-alpine
    restart: always
    ports:
      - 6380:6379
    volumes:
      - redis-data-test:/data
    networks:
      - test-network

  test-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - logs-data-test:/home/node/app/logs
    command: npm run test:unit
    networks:
      - test-network

  test-integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - logs-data-test:/home/node/app/logs
    command: sh -c "npx prisma migrate deploy --schema ./prisma/schema.prisma && npm run test:integration"
    networks:
      - test-network

  test-e2e:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      db-test:
        condition: service_healthy
      redis-test:
        condition: service_started
    volumes:
      - logs-data-test:/home/node/app/logs
    command: sh -c "npx prisma migrate deploy --schema ./prisma/schema.prisma && npm run test:e2e"
    networks:
      - test-network
