volumes:
  postgres-db:
  redis-data:
  weather-data:
  subscription-data:
  notification-data:
  gateway-data:
  email-data:

networks:
  dev-network:
    driver: bridge
  weather-api-dev:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - apps/subscription/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    user: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - weather-api-dev

  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']
    networks:
      - weather-api-dev

  weather:
    container_name: weather
    build:
      context: .
      dockerfile: apps/weather/Dockerfile.dev
    env_file:
      - apps/weather/.env
    ports:
      - '3001:3001'
      - '5051:5051'
    volumes:
      - .:/app
      - weather-data:/app/node_modules
    depends_on:
      redis:
        condition: service_started
    networks:
      - weather-api-dev

  subscription:
    container_name: subscription
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile.dev
    env_file:
      - apps/subscription/.env
    ports:
      - '5052:5052'
    volumes:
      - .:/app
      - subscription-data:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - weather-api-dev

  notification:
    container_name: notification
    build:
      context: .
      dockerfile: apps/notification/Dockerfile.dev
    env_file:
      - apps/notification/.env
    ports:
      - '5053:5053'
    volumes:
      - .:/app
      - notification-data:/app/node_modules
    depends_on:
      weather:
        condition: service_started
      subscription:
        condition: service_started
      email:
        condition: service_started
    networks:
      - weather-api-dev

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile.dev
    env_file:
      - apps/gateway/.env
    ports:
      - '5055:5055'
    volumes:
      - .:/app
      - gateway-data:/app/node_modules
    depends_on:
      weather:
        condition: service_started
      subscription:
        condition: service_started
      email:
        condition: service_started
    networks:
      - weather-api-dev

  email:
    container_name: email
    build:
      context: .
      dockerfile: apps/email/Dockerfile.dev
    env_file:
      - apps/email/.env
    ports:
      - '5054:5054'
    volumes:
      - .:/app
      - email-data:/app/node_modules
    networks:
      - weather-api-dev
