networks:
  dev-network:
    driver: bridge
  weather-api:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']
    networks:
      - weather-api

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - apps/subscription/.env
    ports:
      - 5433:5432
    user: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - weather-api

  weather:
    container_name: weather
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    env_file:
      - apps/weather/.env
    ports:
      - '5051:5051'
    depends_on:
      redis:
        condition: service_started
    networks:
      - weather-api

  subscription:
    container_name: subscription
    build:
      context: .
      dockerfile: apps/subscription/Dockerfile
    env_file:
      - apps/subscription/.env
    ports:
      - '5052:5052'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - weather-api

  email:
    container_name: email
    build:
      context: .
      dockerfile: apps/email/Dockerfile
    env_file:
      - apps/email/.env
    ports:
      - '5054:5054'
    networks:
      - weather-api

  notification:
    container_name: notification
    build:
      context: .
      dockerfile: apps/notification/Dockerfile
    env_file:
      - apps/notification/.env
    ports:
      - '5053:5055'
    depends_on:
      email:
        condition: service_started
      subscription:
        condition: service_started
      weather:
        condition: service_started
    networks:
      - weather-api

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    env_file:
      - apps/gateway/.env
    ports:
      - '5055:5055'
    depends_on:
      email:
        condition: service_started
      subscription:
        condition: service_started
      weather:
        condition: service_started
    networks:
      - weather-api
