networks:
  dev-network:
    driver: bridge
  weather-api:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '--save', '60', '1', '--appendonly', 'yes']
    networks:
      - weather-api

  weather:
    container_name: weather
    build:
      context: .
      dockerfile: apps/weather/Dockerfile
    env_file:
      - apps/weather/.env
    ports:
      - '5051:5051'
    depends_on:
      redis:
        condition: service_started
    networks:
      - weather-api
