syntax = "proto3";

package subscription;

enum Frequency {
  hourly = 0;
  daily = 1;
}

service SubscriptionService {
  rpc Subscribe (SubscribeRequest) returns (SubscribeResponse);
  rpc Confirm (ConfirmRequest) returns (ActionResponse);
  rpc Unsubscribe (UnsubscribeRequest) returns (ActionResponse);

  rpc GetByFrequency (GetByFrequencyRequest) returns (GetByFrequencyResponse);
  rpc DeleteUnconfirmed (DeleteUnconfirmedRequest) returns (DeleteUnconfirmedResponse);
}

message SubscribeRequest {
  string email = 1;
  string city = 2;
  Frequency frequency = 3;
}

message ConfirmRequest {
  string token = 1;
}

message UnsubscribeRequest {
  string token = 1;
}

message GetByFrequencyRequest {
  Frequency frequency = 1;
}

message GetByFrequencyResponse {
  repeated SubscriptionEntity subscriptions = 1;
}

message DeleteUnconfirmedRequest {}

message DeleteUnconfirmedResponse {
  int32 count = 1;
}

message ActionResponse {
  string message = 1;
}

message SubscribeResponse {
  string email = 1;
  string token = 2;
}

message SubscriptionEntity {
  int64 subscriptionId = 1;
  string email = 2;
  string city = 3;
  Frequency frequency = 4;
  bool confirmed = 5;
}