FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npx prisma generate --schema ./apps/subscription/prisma/schema.prisma

EXPOSE 5052

CMD ["npm", "run", "start:subscription:dev"]