FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npx prisma generate --schema ./apps/subscription/prisma/schema.prisma

RUN npm run build subscription

CMD ["sh", "-c", "npm run subscription:migration && npm run start:subscription"]