FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY libs/ ./libs/

RUN npm i

COPY . .

RUN npx prisma generate --schema ./apps/subscription/prisma/schema.prisma

EXPOSE 5052

CMD ["sh", "-c", "npm run subscription:migration && npm run start:subscription:dev"]