name: Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose -f docker-compose.test.yml build

      - name: Start Integration Tests
        run: docker compose -f docker-compose.test.yml up --abort-on-container-exit test-runner