name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and dependencies
        uses: ./.github/actions/setup-node

      - name: Run unit tests
        run: npm run test:unit
